import type { Block, CollectionConfig, Field, Plugin } from 'payload'

/**
 * Ukrainian labels for collections generated by third-party plugins
 * (payload-auth, form-builder, search, MCP) that expose no translation API —
 * their labels/descriptions are hardcoded English strings. This plugin runs
 * last and rewrites those strings in the sanitized config.
 *
 * Only fields explicitly listed in the map are touched; everything else is
 * left as the plugin produced it.
 */

type FieldMap = Record<
  string,
  {
    blocks?: Record<string, { fields?: FieldMap; labels?: { plural: string; singular: string } }>
    description?: string
    fields?: FieldMap
    label?: string
    labels?: { plural: string; singular: string }
    options?: Record<string, string>
  }
>

type CollectionMap = {
  description?: string
  fields?: FieldMap
  group?: string
  labels?: { plural: string; singular: string }
}

const commonFormFieldProps: FieldMap = {
  blockName: { label: 'Назва блока' },
  defaultValue: { label: 'Значення за замовчуванням' },
  label: { label: 'Мітка' },
  name: { label: 'Імʼя поля (латиницею, без спецсимволів)' },
  placeholder: { label: 'Підказка (placeholder)' },
  required: { label: 'Обовʼязкове' },
  width: { label: 'Ширина поля (%)' },
  options: {
    label: 'Варіанти',
    labels: { singular: 'Варіант', plural: 'Варіанти' },
    fields: {
      label: { label: 'Мітка' },
      value: { label: 'Значення' },
    },
  },
}

const formFieldBlocks: NonNullable<FieldMap[string]['blocks']> = {
  checkbox: { labels: { singular: 'Прапорець', plural: 'Прапорці' }, fields: commonFormFieldProps },
  country: { labels: { singular: 'Країна', plural: 'Країни' }, fields: commonFormFieldProps },
  email: { labels: { singular: 'Email', plural: 'Email' }, fields: commonFormFieldProps },
  message: {
    labels: { singular: 'Повідомлення', plural: 'Повідомлення' },
    fields: { ...commonFormFieldProps, message: { label: 'Текст повідомлення' } },
  },
  number: { labels: { singular: 'Число', plural: 'Числа' }, fields: commonFormFieldProps },
  select: {
    labels: { singular: 'Випадний список', plural: 'Випадні списки' },
    fields: commonFormFieldProps,
  },
  state: { labels: { singular: 'Штат', plural: 'Штати' }, fields: commonFormFieldProps },
  text: {
    labels: { singular: 'Текстове поле', plural: 'Текстові поля' },
    fields: commonFormFieldProps,
  },
  textarea: {
    labels: { singular: 'Багаторядкове поле', plural: 'Багаторядкові поля' },
    fields: commonFormFieldProps,
  },
}

const collectionMap: Record<string, CollectionMap> = {
  redirects: {
    labels: { singular: 'Перенаправлення', plural: 'Перенаправлення' },
  },
  forms: {
    labels: { singular: 'Форма', plural: 'Форми' },
    fields: {
      title: { label: 'Назва' },
      fields: {
        label: 'Поля форми',
        labels: { singular: 'Поле', plural: 'Поля' },
        blocks: formFieldBlocks,
      },
      submitButtonLabel: { label: 'Текст кнопки надсилання' },
      confirmationType: {
        label: 'Тип підтвердження',
        description:
          'Оберіть, що станеться після надсилання форми: показ повідомлення на сторінці чи перенаправлення на іншу сторінку.',
        options: {
          message: 'Повідомлення',
          redirect: 'Перенаправлення',
        },
      },
      confirmationMessage: { label: 'Повідомлення підтвердження' },
      redirect: {
        label: 'Перенаправлення',
        fields: {
          url: { label: 'URL для перенаправлення' },
          type: { label: 'Тип' },
          reference: { label: 'Документ для перенаправлення' },
        },
      },
      emails: {
        label: 'Листи',
        labels: { singular: 'Лист', plural: 'Листи' },
        description:
          'Надсилайте власні листи після надсилання форми. Для кількох одержувачів розділяйте адреси комами. Щоб підставити значення з форми, обгорніть імʼя поля подвійними фігурними дужками, напр. {{firstName}}. {{*}} виведе всі дані, а {{*:table}} — у вигляді HTML-таблиці в листі.',
        fields: {
          emailTo: { label: 'Кому' },
          cc: { label: 'Копія (CC)' },
          bcc: { label: 'Прихована копія (BCC)' },
          replyTo: { label: 'Відповідати на (Reply-To)' },
          emailFrom: { label: 'Від кого' },
          subject: { label: 'Тема' },
          message: { label: 'Текст листа' },
        },
      },
    },
  },
  'form-submissions': {
    labels: { singular: 'Відповідь форми', plural: 'Відповіді форм' },
    fields: {
      form: { label: 'Форма' },
      submissionData: {
        label: 'Дані відповіді',
        labels: { singular: 'Значення', plural: 'Значення' },
        fields: {
          field: { label: 'Поле' },
          value: { label: 'Значення' },
        },
      },
    },
  },
  search: {
    labels: { singular: 'Результат пошуку', plural: 'Результати пошуку' },
    description:
      'Колекція результатів пошуку, що створюються автоматично. Використовується глобальним пошуком по сайту й оновлюється під час створення чи зміни документів у CMS.',
    fields: {
      title: { label: 'Заголовок' },
      priority: { label: 'Пріоритет' },
      doc: { label: 'Документ' },
      docUrl: { label: 'URL документа' },
      slug: { label: 'Slug' },
      collectionType: { label: 'Тип колекції' },
    },
  },
  users: {
    group: 'Автентифікація',
    fields: {
      name: { label: 'Імʼя', description: 'Відображуване імʼя користувача' },
      email: { label: 'Email', description: 'Електронна пошта користувача' },
      emailVerified: {
        label: 'Email підтверджено',
        description: 'Чи підтверджено електронну пошту користувача',
      },
      image: { label: 'Зображення', description: 'Аватар користувача (URL)' },
      role: {
        label: 'Роль',
        description: 'Роль або ролі користувача',
        options: {
          admin: 'Адміністратор',
          learner: 'Учасник',
        },
      },
      // Join fields keep better-auth's singular model keys as names.
      account: { label: 'Облікові записи' },
      session: { label: 'Сесії' },
    },
  },
  sessions: {
    labels: { singular: 'Сесія', plural: 'Сесії' },
    group: 'Автентифікація',
    description: 'Активні сесії користувачів. Використовуються для входу за токеном сесії.',
    fields: {
      user: { label: 'Користувач', description: 'Користувач, якому належить сесія' },
      token: { label: 'Токен', description: 'Унікальний токен сесії' },
      expiresAt: { label: 'Дійсна до', description: 'Дата й час завершення сесії' },
      ipAddress: { label: 'IP-адреса', description: 'IP-адреса пристрою' },
      userAgent: { label: 'User Agent', description: 'Інформація про браузер і пристрій' },
      impersonatedBy: {
        label: 'Від імені',
        description: 'Адміністратор, який діє від імені користувача в цій сесії',
      },
    },
  },
  accounts: {
    labels: { singular: 'Обліковий запис', plural: 'Облікові записи' },
    group: 'Автентифікація',
    description: 'Облікові записи користувачів у провайдерів автентифікації.',
    fields: {
      user: { label: 'Користувач', description: 'Користувач, якому належить обліковий запис' },
      accountId: {
        label: 'ID облікового запису',
        description:
          'Ідентифікатор облікового запису від SSO-провайдера (для входу за паролем збігається з ID користувача)',
      },
      providerId: { label: 'Провайдер', description: 'Ідентифікатор провайдера автентифікації' },
      accessToken: { label: 'Access token', description: 'Токен доступу, виданий провайдером' },
      refreshToken: { label: 'Refresh token', description: 'Токен оновлення, виданий провайдером' },
      accessTokenExpiresAt: {
        label: 'Access token дійсний до',
        description: 'Дата й час завершення дії токена доступу',
      },
      refreshTokenExpiresAt: {
        label: 'Refresh token дійсний до',
        description: 'Дата й час завершення дії токена оновлення',
      },
      scope: { label: 'Scope', description: 'Області доступу облікового запису' },
      idToken: { label: 'ID token', description: 'ID-токен від провайдера' },
      password: {
        label: 'Пароль (хеш)',
        description: 'Хешований пароль — використовується для входу за email і паролем',
      },
    },
  },
  verifications: {
    labels: { singular: 'Верифікація', plural: 'Верифікації' },
    group: 'Автентифікація',
    description: 'Запити верифікації (підтвердження email, скидання пароля тощо).',
    fields: {
      identifier: { label: 'Ідентифікатор', description: 'Ідентифікатор запиту верифікації' },
      value: { label: 'Значення', description: 'Значення, що підлягає перевірці' },
      expiresAt: { label: 'Дійсний до', description: 'Дата й час завершення дії запиту' },
    },
  },
  'admin-invitations': {
    labels: { singular: 'Запрошення адміністратора', plural: 'Запрошення адміністраторів' },
    group: 'Автентифікація',
    fields: {
      role: {
        label: 'Роль',
        options: {
          admin: 'Адміністратор',
          learner: 'Учасник',
        },
      },
      token: { label: 'Токен' },
      url: { label: 'Посилання-запрошення' },
    },
  },
  'payload-mcp-api-keys': {
    labels: { singular: 'API-ключ', plural: 'API-ключі' },
    description:
      'API-ключі визначають, до яких колекцій, ресурсів, інструментів і промптів мають доступ MCP-клієнти',
    fields: {
      user: { label: 'Користувач', description: 'Користувач, з яким повʼязано API-ключ' },
      label: { label: 'Назва', description: 'Зрозуміла назва API-ключа' },
      description: { label: 'Опис', description: 'Призначення API-ключа' },
    },
  },
}

/** English tab labels inside plugin-generated collections. */
const tabLabelMap: Record<string, string> = {
  Prompts: 'Промпти',
  Resources: 'Ресурси',
  Tools: 'Інструменти',
}

const applyFieldMap = (fields: Field[], map: FieldMap): void => {
  for (const field of fields) {
    if (field.type === 'tabs') {
      for (const tab of field.tabs) {
        if (typeof tab.label === 'string' && tabLabelMap[tab.label]) {
          tab.label = tabLabelMap[tab.label]
        }
        applyFieldMap(tab.fields, map)
      }
      continue
    }

    if (field.type === 'row' || field.type === 'collapsible') {
      applyFieldMap(field.fields, map)
      continue
    }

    if (!('name' in field) || !field.name) continue
    const entry = map[field.name]
    if (!entry) continue

    if (entry.label !== undefined) field.label = entry.label
    if (entry.labels && (field.type === 'array' || field.type === 'blocks')) {
      field.labels = entry.labels
    }
    if (entry.description !== undefined) {
      field.admin = { ...field.admin, description: entry.description }
    }
    if (entry.options && 'options' in field && Array.isArray(field.options)) {
      field.options = field.options.map((option) => {
        if (typeof option === 'string') {
          return entry.options![option] ? { label: entry.options![option], value: option } : option
        }
        const translated = entry.options![option.value]
        return translated ? { ...option, label: translated } : option
      })
    }
    if (entry.fields && 'fields' in field && Array.isArray(field.fields)) {
      applyFieldMap(field.fields, entry.fields)
    }
    if (entry.blocks && field.type === 'blocks' && Array.isArray(field.blocks)) {
      for (const block of field.blocks as Block[]) {
        const blockEntry = entry.blocks[block.slug]
        if (!blockEntry) continue
        if (blockEntry.labels) block.labels = blockEntry.labels
        if (blockEntry.fields) applyFieldMap(block.fields, blockEntry.fields)
      }
    }
  }
}

const applyCollectionMap = (collection: CollectionConfig, map: CollectionMap): void => {
  if (map.labels) collection.labels = map.labels
  if (map.description !== undefined || map.group !== undefined) {
    collection.admin = {
      ...collection.admin,
      ...(map.description !== undefined && { description: map.description }),
      ...(map.group !== undefined && { group: map.group }),
    }
  }
  if (map.fields) applyFieldMap(collection.fields, map.fields)
}

export const ukrainianAdmin: Plugin = (config) => {
  for (const collection of config.collections ?? []) {
    const map = collectionMap[collection.slug]
    if (map) applyCollectionMap(collection, map)

    // The payload-auth invite button is hardcoded English — swap in our
    // Ukrainian version (it reuses the same server endpoints).
    if (collection.slug === 'users') {
      const description = collection.admin?.components?.Description
      if (
        description &&
        typeof description === 'object' &&
        'path' in description &&
        typeof description.path === 'string' &&
        description.path.includes('AdminInviteButton')
      ) {
        description.path = '@/components/admin/InviteUserButton#InviteUserButton'
      }
    }
  }

  return config
}
