name: Delete Neon branch on PR close

on:
  pull_request:
    types: [closed]

jobs:
  delete-neon-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: sleep 1200
      - run: npm i -g neonctl
      - run: neonctl branches delete "preview/${{ github.head_ref }}" --project-id sweet-night-33633526
        env:
          NEON_API_KEY: ${{ secrets.NEON_API_KEY }}
